---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archiveteam-warrior
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/toof-jp/infra
    targetRevision: HEAD
    path: kubernetes/applications/archiveteam-warrior
  destination:
    server: https://kubernetes.default.svc
    namespace: archiveteam-warrior
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
