---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bbs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/toof-jp/infra
    targetRevision: HEAD
    path: kubernetes/applications/bbs
  destination:
    server: https://kubernetes.default.svc
    namespace: bbs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
