---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shisha-log
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/toof-jp/infra
    targetRevision: HEAD
    path: kubernetes/applications/shisha-log
  destination:
    server: https://kubernetes.default.svc
    namespace: shisha-log
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
