---
apiVersion: v1
kind: Namespace
metadata:
  name: archiveteam-warrior
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiveteam-warrior
  namespace: archiveteam-warrior
spec:
  selector:
    matchLabels:
      app: archiveteam-warrior
  template:
    metadata:
      labels:
        app: archiveteam-warrior
    spec:
      containers:
      - name: archiveteam-warrior
        image: atdr.meo.ws/archiveteam/warrior-dockerfile:latest
        ports:
        - containerPort: 8001
        env:
        - name: DOWNLOADER
          value: toof-jp
        - name: SELECTED_PROJECT
          value: gooblog
        - name: CONCURRENT_ITEMS
          value: "2"
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: archiveteam-warrior
  namespace: archiveteam-warrior
spec:
  type: NodePort
  selector:
    app: archiveteam-warrior
  ports:
  - nodePort: 30163
    port: 8001
    targetPort: 8001
