---
apiVersion: v1
kind: Namespace
metadata:
  name: archiveteam-warrior
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiveteam-warrior
  namespace: archiveteam-warrior
spec:
  selector:
    matchLabels:
      app: archiveteam-warrior
  template:
    metadata:
      labels:
        app: search-backend
    spec:
      containers:
      - name: archiveteam-warrior
        image: atdr.meo.ws/archiveteam/warrior-dockerfile@sha256:09ec5eb0ff6fcfd95c34582780015f2c283a6a91013098d1b91a46882ca29bfc
        ports:
        - containerPort: 3001
        env:
        - name: DOWNLOADER
          value: toof.jp
        - name: SELECTED_PROJECT
          value: auto
        - name: CONCURRENT_ITEMS
          value: 2
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: archiveteam-warrior
  namespace: archiveteam-warrior
spec:
  type: NodePort
  selector:
    app: archiveteam-warrior
  ports:
  - nodePort: 30163
    port: 3001
    targetPort: 3001
