---
apiVersion: v1
kind: Namespace
metadata:
  name: archiveteam-warrior
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiveteam-warrior
  namespace: archiveteam-warrior
spec:
  selector:
    matchLabels:
      app: archiveteam-warrior
  template:
    metadata:
      labels:
        app: archiveteam-warrior
    spec:
      containers:
      - name: archiveteam-warrior
        image: atdr.meo.ws/archiveteam/warrior-dockerfile:latest
        ports:
        - name: http
          containerPort: 8001
        env:
        - name: DOWNLOADER
          value: toof-jp
        - name: SELECTED_PROJECT
          value: gooblog
        - name: CONCURRENT_ITEMS
          value: "6" # max value
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: archiveteam-warrior
  namespace: archiveteam-warrior
spec:
  selector:
    app: archiveteam-warrior
  ports:
  - name: http
    port: 8001
    targetPort: 8001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: archiveteam-warrior
  namespace: archiveteam-warrior
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: warrior.toof.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: archiveteam-warrior
            port:
              number: 8001
