---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: cloudflare
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: cloudflare-secret
  data:
  - secretKey: account-id
    remoteRef:
      key: cloudflare-account-id
  - secretKey: tunnel-name
    remoteRef:
      key: cloudflare-tunnel-name
  - secretKey: api-token
    remoteRef:
      key: cloudflare-api-token
