---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-webhook
  namespace: bbs
spec:
  selector:
    matchLabels:
      app: discord-webhook
  template:
    metadata:
      labels:
        app: discord-webhook
    spec:
      containers:
      - name: discord-webhook
        image: ghcr.io/toof-jp/discord-webhook:sha-4319bdc
        envFrom:
        - secretRef:
            name: postgres-secret
        - secretRef:
            name: discord-webhook-secret
