---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seacrh-backend-external-secret
  namespace: bbs
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: database-secret
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: bbs-database-url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-external-secret
  namespace: bbs
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: discord-webhook-secret
  data:
  - secretKey: WEBHOOK_URL
    remoteRef:
      key: bbs-discord-webhook-url
  - secretKey: IMAGE_URL_PREFIX
    remoteRef:
      key: bbs-discord-webhook-image-url-prefix
  - secretKey: REDIS_URL
    remoteRef:
      key: bbs-discord-webhook-redis-url
