---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-external-secret
  namespace: bbs
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: discord-webhook-secret
  data:
  - secretKey: WEBHOOK_URL
    remoteRef:
      key: bbs-discord-webhook-url
  - secretKey: IMAGE_URL_PREFIX
    remoteRef:
      key: bbs-discord-webhook-image-url-prefix
  - secretKey: REDIS_URL
    remoteRef:
      key: bbs-discord-webhook-redis-url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
  namespace: bbs
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    template:
      type: Opaque
      data:
        POSTGRES_USER: user
        POSTGRES_DB: bbs
        POSTGRES_PASSWORD: "{{ .password }}"
        DATABASE_URL: >-
          postgresql://user:{{ .password }}@postgres:5432/bbs
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: "postgres-password"
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: password
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 42
      digits: 0
      symbols: 0
      symbolCharacters: ""
      allowRepeat: true
