---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-backend
  namespace: bbs
spec:
  selector:
    matchLabels:
      app: search-backend
  template:
    metadata:
      labels:
        app: search-backend
    spec:
      containers:
      - name: search-backend
        image: ghcr.io/toof-jp/bbs-search-backend:sha-2f6894e
        ports:
        - name: http
          containerPort: 3000
        envFrom:
        - secretRef:
            name: database-secret
---
apiVersion: v1
kind: Service
metadata:
  name: search-backend
  namespace: bbs
spec:
  type: NodePort
  selector:
    app: search-backend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000
